steps:
  - name: node
    entrypoint: npm
    args: ["ci", "--prefer-offline", "--no-audit"]

  - name: 'gcr.io/cloud-builders/npm'
    secretEnv: ["VITE_API_BACK_URL"]
    args:
      - "-c"
      - |
        echo "VITE_API_BACK_URL=$$VITE_API_BACK_URL" > .env
        cat .env  # Verificar que el secreto se está pasando correctamente
        npm run build

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rm", "-r", "gs://cepr-front/*"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "dist/", "gs://cepr-front"]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/tu-proyecto/secrets/VITE_API_BACK_URL/versions/latest
      env: VITE_API_BACK_URL
